---
name: "Docker Image Cache Action"
description: "Cache Docker images"
author: "Zentria OÜ"

inputs:
  cache-suffix:
    description: "Cache suffix (e.g. cache based on 3rd party tooling version)"
    required: false
    default: "default"

outputs:
  cache-hit:
    description: "Whether cache was hit"

runs:
  using: "node16"
  main: "dist/index.js"
  post: "dist/post-index.js"
  post-if: "success()"
