name: "Cache Docker images"

on:
  workflow_dispatch:

jobs:
  cache-images:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out sources"
        id: "checkout"
        uses: "actions/checkout@v3"

      - name: "Setup image cache"
        id: "cache"
        uses: "actions/cache@v3"
        with:
          path: "cache"
          key: "docker-${{ runner.os }}-${{ runner.arch }}-001"

      - name: "Store stock images list"
        run: |
          bash -x ./dump_images.sh > ./ignored.txt

      - name: "Restore image cache"
        run: |
          bash -x ./restore.sh

      - name: "Do things in containers"
        run: |
          set -euo pipefail

          while read -r image; do
            docker run --rm --name "testing" --entrypoint="" "${image}" /bin/sh -c "echo testing" || true
          done < ./test_images.txt

      - name: "Cache images"
        run: |
          bash -x ./cache.sh ./ignored.txt
