name: "Cache Docker images"

on:
  workflow_dispatch:

jobs:
  cache-images:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out sources"
        id: "checkout"
        uses: "actions/checkout@v3"

      - name: "Setup Supabase CLI"
        id: "setup-supabase"
        uses: "supabase/setup-cli@v1"
        with:
          version: "latest"

      - name: "Setup image cache"
        id: "cache"
        uses: "actions/cache@v3"
        with:
          path: "cache"
          key: "docker-${{ runner.os }}-${{ runner.arch }}-supabase-${{ steps.setup-supabase.outputs.version }}"

      - name: "Store stock images list"
        run: |
          bash -x ./dump_images.sh > ./ignored.txt

      - name: "Restore image cache"
        run: |
          bash -x ./restore.sh

      - name: "Start Supabase local development setup"
        run: |
         supabase start

      - name: "Cache images"
        run: |
          bash -x ./cache.sh ./ignored.txt
